### ISSUE TITLE
Print commands in CameraTheremin.py should be updated for Python 3+

### ISSUE THREAD

**Issue by dawsonv** [aneeshdurg/CameraTheremin#1]
Print commands in CameraTheremin.py should be updated for Python 3+. For instance, parentheses should be inserted in some calls to print. I'm not familiar with the print syntax when this many arguments are involved, but someone who is should correct it.

**Comment by aneeshdurg** [comment]
It seems like back when I did this, I didn't know that print could take multiple arguments... every call to print has exactly one argument as far as I can tell so it shouldn't be too hard to make this work for both 2 and 3. There's probably a broader issue here of refactoring the entire project.
